### ISSUE TITLE
Internal server error when clicking the tab

### ISSUE THREAD

**Issue by ikomhoog** [nextcloud/serverinfo#278]
I am a bit overwhelmed by the info that I get spewed at me, I'm also not a big user of Nextcloud.
If I need to provide anything else, please explain where I can get it.
Apps also wouldn't update so my install might just be broken.

### Steps to reproduce
1. install app
2. try to look at settings -> system
3. internal server error

### Expected behaviour
get shown a page with system info?

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**: nux 5.10.1-Unraid #1 SMP Thu Dec 17 11:41:39 PST 2020 x86_64

**Web server:**  Apache/2.4.38 (Debian) (apache2handler)

**Database:** sqlite3 3.27.2

**PHP version:** 7.4.15
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** (see Nextcloud admin page) 21.0.0 - 21.0.0.18

**Where did you install Nextcloud from:** "unknown" according to the server configuration detail, but its docker

**List of activated apps:** 

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - admin_audit: 1.11.0
 - cloud_federation_api: 1.4.0
 - dashboard: 7.1.0
 - dav: 1.17.1
 - deck: 1.3.0
 - federatedfilesharing: 1.11.0
 - files: 1.16.0
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - firstrunwizard: 2.10.0
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - nextcloud_announcements: 1.10.0
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - password_policy: 1.11.0
 - photos: 1.3.0
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - recommendations: 1.0.0
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - support: 1.4.0
 - survey_client: 1.9.0
 - text: 3.2.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.0
 - updatenotification: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.5.0
 - weather_status: 1.1.0
 - workflowengine: 2.3.0
Disabled:
 - comments
 - contactsinteraction
 - encryption
 - federation
 - files_external
 - systemtags
 - user_ldap
```

**Nextcloud configuration:**

```
{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "192.168.178.250"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "sqlite3",
    "version": "21.0.0.18",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "overwritehost": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "debug": true,
    "loglevel": 3,
    "maintenance": false,
    "theme": "",
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
}
```

### Client configuration
**Browser:** chrome

**Operating system:** windows 10

#### Nextcloud log (data/owncloud.log)
a single piece of the wall of text
```
{"reqId":"1bN9Jv7NdpOygDmwT2al","level":3,"time":"2021-02-23T20:07:00+00:00","remoteAddr":"***myIP***","user":"ikomhoog","app":"index","method":"GET","url":"/settings/admin/serverinfo","message":{"Exception":"Exception","Message":"Call to undefined method OC\\DB\\ConnectionAdapter::getParams()","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AdminSettingsController"},"index"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AdminSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"serverinfo","_route":"settings.AdminSettings.index"}]},{"file":"/var/www/html/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/admin/serverinfo"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":159,"Previous":{"Exception":"Error","Message":"Call to undefined method OC\\DB\\ConnectionAdapter::getParams()","Code":0,"Trace":[{"file":"/var/www/html/apps/serverinfo/lib/DatabaseStatistics.php","line":53,"function":"databaseSize","class":"OCA\\ServerInfo\\DatabaseStatistics","type":"->","args":[]},{"file":"/var/www/html/apps/serverinfo/lib/Settings/AdminSettings.php","line":116,"function":"getDatabaseStatistics","class":"OCA\\ServerInfo\\DatabaseStatistics","type":"->","args":[]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":138,"function":"getForm","class":"OCA\\ServerInfo\\Settings\\AdminSettings","type":"->","args":[]},{"file":"/var/www/html/apps/settings/lib/Controller/AdminSettingsController.php","line":83,"function":"formatSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":[[[{"__class__":"OCA\\ServerInfo\\Settings\\AdminSettings"}]]]},{"file":"/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":149,"function":"getSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":["serverinfo"]},{"file":"/var/www/html/apps/settings/lib/Controller/AdminSettingsController.php","line":68,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":["admin","serverinfo"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"index","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":["serverinfo"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AdminSettingsController"},"index"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AdminSettingsController"},"index"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AdminSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"serverinfo","_route":"settings.AdminSettings.index"}]},{"file":"/var/www/html/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/admin/serverinfo"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/apps/serverinfo/lib/DatabaseStatistics.php","Line":115},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36","version":"21.0.0.18"}
```

#### Browser log
```
Internal Server Error
The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.

Technical details
Remote Address: ***MyIP***
Request ID: eCd6rZESf8ExcUJ4yHAI
Type: Exception
Code: 0
Message: Call to undefined method OC\DB\ConnectionAdapter::getParams()
File: /var/www/html/lib/private/AppFramework/Http/Dispatcher.php
Line: 159

Trace
#0 /var/www/html/lib/private/AppFramework/App.php(157): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Settings\Controller\AdminSettingsController), 'index')
#1 /var/www/html/lib/private/Route/Router.php(302): OC\AppFramework\App::main('OCA\\Settings\\Co...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#2 /var/www/html/lib/base.php(993): OC\Route\Router->match('/settings/admin...')
#3 /var/www/html/index.php(37): OC::handleRequest()
#4 {main}

Previous
#0 /var/www/html/apps/serverinfo/lib/DatabaseStatistics.php(53): OCA\ServerInfo\DatabaseStatistics->databaseSize()
#1 /var/www/html/apps/serverinfo/lib/Settings/AdminSettings.php(116): OCA\ServerInfo\DatabaseStatistics->getDatabaseStatistics()
#2 /var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php(138): OCA\ServerInfo\Settings\AdminSettings->getForm()
#3 /var/www/html/apps/settings/lib/Controller/AdminSettingsController.php(83): OCA\Settings\Controller\AdminSettingsController->formatSettings(Array)
#4 /var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php(149): OCA\Settings\Controller\AdminSettingsController->getSettings('serverinfo')
#5 /var/www/html/apps/settings/lib/Controller/AdminSettingsController.php(68): OCA\Settings\Controller\AdminSettingsController->getIndexResponse('admin', 'serverinfo')
#6 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(218): OCA\Settings\Controller\AdminSettingsController->index('serverinfo')
#7 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(127): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Settings\Controller\AdminSettingsController), 'index')
#8 /var/www/html/lib/private/AppFramework/App.php(157): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Settings\Controller\AdminSettingsController), 'index')
#9 /var/www/html/lib/private/Route/Router.php(302): OC\AppFramework\App::main('OCA\\Settings\\Co...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#10 /var/www/html/lib/base.php(993): OC\Route\Router->match('/settings/admin...')
#11 /var/www/html/index.php(37): OC::handleRequest()
#12 {main}
```

**Comment by vszakats** [comment]
Same error here after upgrading from 20.0.7 to 21.0.0, via the official docker image:

**Internal Server Error** happens on this line, consistently, every time, when accessing `https://<host>/settings/admin/serverinfo`:
https://github.com/nextcloud/serverinfo/blob/d6d3f61ac3e7795da6e1a2edcead1f3d59fce566/lib/DatabaseStatistics.php#L115

`nextcloud.log`:
```
[...],"File":"/var/www/html/apps/serverinfo/lib/DatabaseStatistics.php","Line":115},"CustomMessage":"--"}[...]
```

This functionality worked normally before the upgrade, as tested a few days ago.
