### ISSUE TITLE
could not resolve OCA\ServerInfo\Settings\AdminSection

### ISSUE THREAD

**Issue by mroi** [nextcloud/serverinfo#39]
I have the serverinfo app installed, because it comes standard with Nextcloud 10.0. However, I disabled the app. Now, whenever I enter the admin settings, I get this message in nextcloud.log:

```
Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve OCA\\\\ServerInfo\\\\Settings\\\\AdminSection! Class OCA\\\\ServerInfo\\\\Settings\\\\AdminSection does not exist\",\"Code\":0,\"Trace\":\"#0 …\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(105): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\ServerInfo\\\\\\\\...')\\n#1 …\\\/lib\\\/private\\\/ServerContainer.php(89): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\ServerInfo\\\\\\\\...')\\n#2 …\\\/lib\\\/private\\\/Settings\\\/Manager.php(319): OC\\\\ServerContainer->query('OCA\\\\\\\\ServerInfo\\\\\\\\...')\\n#3 …\\\/lib\\\/private\\\/Settings\\\/Manager.php(354): OC\\\\Settings\\\\Manager->query('OCA\\\\\\\\ServerInfo\\\\\\\\...')\\n#4 …\\\/settings\\\/Controller\\\/AdminSettingsController.php(131): OC\\\\Settings\\\\Manager->getAdminSections()\\n#5 …\\\/settings\\\/Controller\\\/AdminSettingsController.php(70): OC\\\\Settings\\\\Controller\\\\AdminSettingsController->getNavigationParameters('server')\\n#6 [internal function]: OC\\\\Settings\\\\Controller\\\\AdminSettingsController->index('server')\\n#7 …\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#8 …\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\AdminSettingsController), 'index')\\n#9 …\\\/lib\\\/private\\\/AppFramework\\\/App.php(111): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\AdminSettingsController), 'index')\\n#10 …\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('AdminSettingsCo...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#12 …\\\/lib\\\/private\\\/Route\\\/Router.php(293): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#13 …\\\/lib\\\/base.php(967): OC\\\\Route\\\\Router->match('\\\/settings\\\/admin')\\n#14 …\\\/index.php(48): OC::handleRequest()\\n#15 {main}\",\"File\":\"…\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":90}","level":3,"time":"2016-08-26T11:44:57+00:00","method":"GET","url":"…\/index.php\/settings\/admin","user":"michael"}
```

(server path prefixes truncated for privacy)

**Comment by mroi** [comment]
Manually deleting the ServerInfo entries from the database tables `oc_admin_sections` and `oc_admin_settings` fixed the problem for me.

**Comment by MorrisJobke** [comment]
This was fixed with https://github.com/nextcloud/server/pull/1305 (stable10) and https://github.com/nextcloud/server/pull/1287

**Comment by mroi** [comment]
Thanks for the fix and the workaround.

**Comment by enoch85** [comment]
I get this on 12 stable:

```
	OCP\AppFramework\QueryException: Could not resolve OCA\External\Settings\Admin! Class OCA\External\Settings\Admin does not exist
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 117: OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\External\\Se...')
/var/www/nextcloud/lib/private/ServerContainer.php - line 132: OC\AppFramework\Utility\SimpleContainer->query('OCA\\External\\Se...')
/var/www/nextcloud/lib/private/Settings/Manager.php - line 261: OC\ServerContainer->query('OCA\\External\\Se...')
/var/www/nextcloud/lib/private/Settings/Manager.php - line 352: OC\Settings\Manager->query('OCA\\External\\Se...')
/var/www/nextcloud/settings/Controller/AdminSettingsController.php - line 138: OC\Settings\Manager->getAdminSettings('additional')
/var/www/nextcloud/settings/Controller/AdminSettingsController.php - line 72: OC\Settings\Controller\AdminSettingsController->getNavigationParameters('server')
[internal function] OC\Settings\Controller\AdminSettingsController->index('server')
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\AdminSettingsController), 'index')
/var/www/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\AdminSettingsController), 'index')
/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OC\\Settings\\Con...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/nextcloud/lib/base.php - line 1000: OC\Route\Router->match('/settings/admin')
/var/www/nextcloud/index.php - line 40: OC handleRequest()
{main}
```

Any ideas?

**Comment by enoch85** [comment]
cc @MorrisJobke --^

**Comment by enoch85** [comment]
Ooops, different issue. But still, something I should report @MorrisJobke ?

**Comment by MorrisJobke** [comment]
New ticket please
